<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Trellis.EntityFrameworkCore" />
    <PackageReference Include="Trellis.EntityFrameworkCore.Outbox" />
    <PackageReference Include="Trellis.EntityFrameworkCore.Inbox" />
    <PackageReference Include="Trellis.Authorization" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Application\src\Application.csproj" />
  </ItemGroup>
</Project>
